version: '2.4'
services:
  php:
    container_name: user-service-api
    build:
      context: ""
      dockerfile: ./docker/php/Dockerfile
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql

  nginx:
    container_name: user-service-nginx
    image: nginx:1.19.0
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: user-service-mysql
    ports:
      - "127.0.0.1:${DB_PORT}:3306" # define port for local connection
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mysql-vol:/var/lib/mysql/

  mysql-testing:
    image: mysql:8.0
    container_name: user-service-mysql-testing
    ports:
      - "127.0.0.1:3366:3306" # define port for local connection
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mysql-testing-vol:/var/lib/mysql/

volumes:
  mysql-vol:
    driver: local
  mysql-testing-vol:
    driver: local
